__title__ = "msr_smartapi_python"
__description__ = "Angel Broking openApi integration"
__url__ = "https://www.angelbroking.com/"
__download_url__ = "https://github.com/angelbroking-github/smartapi-python"
__version__ = "1.3.8"
__author__ = "ab-smartapi"
__token__ = "ab-smartapi"
__author_email__ = "smartapi.sdk@gmail.com"
